# -*- coding: utf-8 -*-
"""종목 정규화 카탈로그: (정규식, id, 표시명, 부위, 패턴, 장비)"""

FOCUS = {"lower": "하체·힙", "back": "등", "push": "가슴·어깨"}

PATTERN_KO = {
    "abduction": "고관절 외전", "adduction": "고관절 내전", "glute_bridge": "힙 익스텐션",
    "glute_iso": "둔근 고립", "squat": "스쿼트", "squat_machine": "머신 스쿼트",
    "squat_lateral": "측면 스쿼트", "knee_ext": "무릎 신전", "unilateral": "한다리",
    "hinge": "힌지", "hinge_uni": "한다리 힌지", "plyo": "점프·순간력",
    "vert_pull": "수직 당기기", "horiz_pull": "수평 당기기", "horiz_pull_uni": "한팔 당기기",
    "rear_delt": "후면 삼각", "horiz_push": "수평 밀기", "incline_push": "인클라인 밀기",
    "vert_push": "수직 밀기", "vert_push_uni": "한팔 수직 밀기", "chest_iso": "가슴 고립",
    "side_delt": "측면 삼각", "front_delt": "전면 삼각", "triceps": "삼두",
    "conditioning": "컨디셔닝", "full_body": "전신",
}

# 순서 중요: 위에서부터 먼저 매칭
RULES = [
 # ---------- LOWER ----------
 (r'아웃타이',                          "hip_abduction",        "아웃타이 (힙 어브덕션)",        "lower","abduction","machine"),
 (r'이너타이',                          "hip_adduction",        "이너타이 (힙 어덕션)",         "lower","adduction","machine"),
 (r'레그프레스.*패드|패드.*레그프레스',            "leg_press_pad",        "레그프레스 (다리 사이 패드)",     "lower","adduction","machine"),
 (r'힙\s?쓰러스트.*스미스|스미스.*힙\s?쓰러스트',    "hip_thrust_smith",     "힙 쓰러스트 (스미스)",        "lower","glute_bridge","smith"),
 (r'힙\s?쓰러스트',                      "hip_thrust",           "힙 쓰러스트",              "lower","glute_bridge","barbell"),
 (r'몬스터\s?글루트',                     "monster_glute",        "몬스터 글루트",             "lower","glute_iso","machine"),
 (r'스모\s?데드리프트',                    "sumo_deadlift",        "스모 데드리프트",            "lower","hinge","barbell"),
 (r'스티프\s?데드리프트',                   "stiff_deadlift",       "스티프 데드리프트",           "lower","hinge","barbell"),
 (r'케틀벨|스플릿 자세',                    "kb_split_hinge",       "스플릿 자세 케틀벨 힌지",       "lower","hinge_uni","kettlebell"),
 (r'불가리안',                          "bulgarian_split_squat","불가리안 스플릿 스쿼트",        "lower","unilateral","dumbbell"),
 (r'스미스.*스플릿|스플릿.*스미스',             "smith_split_squat",    "스미스 스플릿 스쿼트",        "lower","unilateral","smith"),
 (r'스플릿\s?스쿼트|까치발하고 올라오기',          "split_squat",          "스플릿 스쿼트",            "lower","unilateral","dumbbell"),
 (r'스미스\s?싱글\s?스쿼트',                "smith_single_squat",   "스미스 싱글 스쿼트",          "lower","unilateral","smith"),
 (r'(원레그|원\s?레그|벤치 원레그).*브이|브이.*원\s?레그', "one_leg_v_squat",   "원레그 브이 스쿼트",         "lower","unilateral","machine"),
 (r'원레그 스쿼트|벤치 원레그|벤치에 한|리프트 업|앞쪽에 벤치', "one_leg_squat_bench","원레그 스쿼트 (벤치)",    "lower","unilateral","dumbbell"),
 (r'스케이팅 니업',                       "skating_kneeup",       "원레그 스케이팅 니업",         "lower","unilateral","dumbbell"),
 (r'슬라이드 패드',                       "slide_pad",            "슬라이드 패드 밀기",          "lower","unilateral","bodyweight"),
 (r'워킹런지|워킹 런지',                    "walking_lunge",        "워킹 런지",               "lower","unilateral","dumbbell"),
 (r'굿모닝 익스텐션|브이\s?스쿼트',             "v_squat",              "브이 스쿼트 (굿모닝 익스텐션)",   "lower","squat_machine","machine"),
 (r'핵\s?스쿼트',                       "hack_squat",           "핵 스쿼트",               "lower","squat_machine","machine"),
 (r'레그프레스',                         "leg_press",            "레그프레스",              "lower","squat_machine","machine"),
 (r'레그\s?익스텐션',                     "leg_extension",        "레그 익스텐션",             "lower","knee_ext","machine"),
 (r'티바\s?스쿼트',                      "tbar_squat",           "티바 스쿼트",              "lower","squat","barbell"),
 (r'사이드\s?스쿼트',                     "side_squat",           "사이드 스쿼트",             "lower","squat_lateral","dumbbell"),
 (r'볼\s?스쿼트|벤치\s?스쿼트',              "bench_squat",          "벤치 스쿼트",              "lower","squat","dumbbell"),
 (r'덤벨\s?스쿼트|튕기고 일어나기',             "dumbbell_squat",       "덤벨 스쿼트",              "lower","squat","dumbbell"),
 (r'점프 런지|개구리 점프|스쿼트 점프|스텝버피',      "jump_squat",           "점프 스쿼트·런지",           "lower","plyo","bodyweight"),
 (r'^스쿼트',                          "barbell_squat",        "스쿼트 (바벨)",             "lower","squat","barbell"),
 # ---------- BACK ----------
 (r'덤벨\s?데드리프트',                    "dumbbell_deadlift",    "덤벨 데드리프트",            "back","hinge","dumbbell"),
 (r'데드리프트',                         "deadlift",             "데드리프트",              "back","hinge","barbell"),
 (r'풀업',                            "pullup_assist",        "풀업 (어시스트)",            "back","vert_pull","machine"),
 (r'랫풀다운.*(내로우|narrow)',             "lat_pulldown_narrow",  "랫풀다운 (내로우 그립)",       "back","vert_pull","machine"),
 (r'랫풀다운.*언더',                      "lat_pulldown_under",   "랫풀다운 (언더그립)",         "back","vert_pull","machine"),
 (r'랫풀다운',                          "lat_pulldown",         "랫풀다운",               "back","vert_pull","machine"),
 (r'와이드.*(풀\s?다운|플\s?다운)',           "wide_pulldown",        "와이드 풀다운",             "back","vert_pull","machine"),
 (r'암\s?풀다운',                       "arm_pulldown",         "암 풀다운",               "back","vert_pull","cable"),
 (r'와이드.*로우',                       "wide_cable_row",       "와이드 케이블 로우",          "back","horiz_pull","cable"),
 (r'미들\s?로우',                       "middle_row",           "미들 로우",               "back","horiz_pull","machine"),
 (r'(원\s?암|원암).*덤벨|덤벨.*원\s?암',        "one_arm_dumbbell_row", "원암 덤벨 로우",            "back","horiz_pull_uni","dumbbell"),
 (r'(원\s?암|원암).*머신|머신.*원\s?암',        "one_arm_row_machine",  "원암 로우 머신",            "back","horiz_pull_uni","machine"),
 (r'(원\s?암|원암|케이블 원암).*(로우|로유)',     "one_arm_cable_row",    "원암 케이블 로우",           "back","horiz_pull_uni","cable"),
 (r'바벨\s?로우',                       "barbell_row",          "바벨 로우 (언더그립)",         "back","horiz_pull","barbell"),
 (r'세라밴드 로우|세라 밴드 로우',              "band_row",             "세라밴드 로우",             "back","horiz_pull","band"),
 (r'케이블\s?로우|케이블 로우',               "cable_row",            "케이블 로우 (일자바)",         "back","horiz_pull","cable"),
 (r'페이스\s?풀',                       "face_pull",            "페이스 풀",               "back","rear_delt","cable"),
 # ---------- PUSH ----------
 (r'(인클라인|인크라인).*스미스|스미스.*인클라인',    "incline_bench_smith",  "인클라인 벤치프레스 (스미스)",   "push","incline_push","smith"),
 (r'(인클라인|인크라인).*덤벨|덤벨.*인클라인',      "incline_bench_dumbbell","인클라인 벤치프레스 (덤벨)",   "push","incline_push","dumbbell"),
 (r'(인클라인|인크라인).*바벨',               "incline_bench_barbell","인클라인 벤치프레스 (바벨)",    "push","incline_push","barbell"),
 (r'(인클라인|인크라인)',                   "incline_bench_machine","인클라인 벤치프레스 (머신)",    "push","incline_push","machine"),
 (r'벤치프레스.*플라이',                    "dumbbell_fly",         "덤벨 플라이",              "push","chest_iso","dumbbell"),
 (r'플라이|펙댁|팩덱',                     "fly_machine",          "플라이 머신 (팩덱)",          "push","chest_iso","machine"),
 (r'벤치프레스.*(스미스|머신)',               "bench_press_smith",    "벤치프레스 (스미스)",         "push","horiz_push","smith"),
 (r'벤치프레스.*덤벨|덤벨.*벤치프레스',          "bench_press_dumbbell", "벤치프레스 (덤벨)",          "push","horiz_push","dumbbell"),
 (r'벤치프레스',                        "bench_press_barbell",  "벤치프레스 (바벨)",          "push","horiz_push","barbell"),
 (r'푸쉬업|푸시업',                      "pushup",               "푸쉬업",                "push","horiz_push","bodyweight"),
 (r'밀리터리\s?프레스',                    "military_press_smith", "밀리터리 프레스 (스미스)",      "push","vert_push","smith"),
 (r'비하인드',                          "behind_shoulder_press","비하인드 숄더프레스",         "push","vert_push","barbell"),
 (r'원암 오버헤드|한손씩 번갈아',              "one_arm_ohp",          "원암 오버헤드 프레스",        "push","vert_push_uni","dumbbell"),
 (r'숄더\s?프레스.*머신',                  "shoulder_press_machine","숄더프레스 (머신)",         "push","vert_push","machine"),
 (r'숄더\s?프레스.*덤벨|덤벨.*숄더',           "shoulder_press_dumbbell","숄더프레스 (덤벨)",        "push","vert_push","dumbbell"),
 (r'숄더\s?프레스.*스미스',                 "shoulder_press_smith", "숄더프레스 (스미스)",         "push","vert_push","smith"),
 (r'(오버\s?헤드|오버헤드).*숄더|숄더\s?프레스',   "shoulder_press_barbell","숄더프레스 (바벨·오버헤드)",  "push","vert_push","barbell"),
 (r'세라\s?밴드 레터럴|세라밴드 레터럴',          "band_lateral_raise",   "세라밴드 레터럴 레이즈",       "push","side_delt","band"),
 (r'사레레|레터럴\s?레이즈|사이드 레터럴',         "lateral_raise",        "사이드 레터럴 레이즈 (사레레)",   "push","side_delt","dumbbell"),
 (r'프론트\s?레이즈',                    "cable_front_raise",    "케이블 프론트 레이즈",         "push","front_delt","cable"),
 (r'푸쉬다운|튜빙밴드',                    "band_pushdown",        "밴드 푸쉬다운",             "push","triceps","band"),
 (r'쓰러스트',                         "thruster",             "쓰러스트 (덤벨)",            "push","full_body","dumbbell"),
 # ---------- 기타 ----------
 (r'메드신볼',                         "medball_complex",      "메드신볼 콤플렉스",           "lower","conditioning","medball"),
 (r'아쿠아스윙|사이드스텝',                  "aqua_swing",           "아쿠아 스윙 / 사이드 스텝",     "lower","conditioning","aquabag"),
 (r'아쿠아백',                         "aquabag_calf",         "아쿠아백 스쿼트 카프",         "lower","conditioning","aquabag"),
]

# 기록엔 없지만 같은 패턴으로 넣을 수 있는 익숙한 대체 종목
EXTRAS = [
 ("romanian_deadlift",  "루마니안 데드리프트",   "lower","hinge","barbell"),
 ("goblet_squat",       "고블릿 스쿼트",       "lower","squat","dumbbell"),
 ("step_up",            "박스 스텝업",        "lower","unilateral","dumbbell"),
 ("cable_kickback",     "케이블 킥백",        "lower","glute_iso","cable"),
 ("seated_row",         "시티드 로우 (머신)",   "back","horiz_pull","machine"),
 ("straight_arm_pulldown","스트레이트 암 풀다운", "back","vert_pull","cable"),
 ("reverse_pec_deck",   "리버스 팩덱",        "back","rear_delt","machine"),
 ("chest_press_machine","체스트 프레스 (머신)",  "push","horiz_push","machine"),
 ("arnold_press",       "아놀드 프레스",       "push","vert_push","dumbbell"),
 ("cable_lateral_raise","케이블 레터럴 레이즈",  "push","side_delt","cable"),
 ("cable_hip_abduction","케이블 힙 어브덕션",   "lower","abduction","cable"),
 ("band_hip_abduction", "밴드 사이드 워크",     "lower","abduction","band"),
 ("copenhagen_plank",   "코펜하겐 플랭크",      "lower","adduction","bodyweight"),
 ("chest_supported_row","체스트 서포티드 로우",  "back","horiz_pull_uni","machine"),
 ("dumbbell_rear_lateral","덤벨 리어 레터럴",   "back","rear_delt","dumbbell"),
 ("nordic_curl",        "노르딕 컬 (햄스트링)",  "lower","hinge_uni","bodyweight"),
]
